version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile --warnings-as-errors
      - run: mix compile
      - run:
          command: mix compile --warnings-as-errors
          environment:
            MIX_ENV: test
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum "mix.lock" }}
            - v1-plt-cache
      - run: mix dialyzer --plt
      - run: mix dialyzer --halt-exit-status
      - run: mix credo --strict --ignore linelength -a
      - run:
          command: mix coveralls.circle --include bench
          environment:
            MIX_ENV: test
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
